<div class="panel panel-default" style="margin: 0 auto; width: 300px;">
    <div class="panel-heading text-center">
        <span class="glyphicon glyphicon-camera"></span> Identifique-se
    </div>
    <div class="panel-body">
        <?php if (!isset($_SESSION['player'])) { ?>
            <div class="row">
                <form class="form-horizontal" method="post" action="<?= $this->link('/cardgame/registro') ?>">
                    <div class="form-group col-lg-12">
                        <div class="col-lg-12">
                            <label>Nome</label>
                            <input class="form-control" name="player" placeholder="Nome"/>
                        </div>
                    </div>
                    <div class="form-group col-lg-12">
                        <div class="col-lg-12">
                            <button class="form-control btn btn-primary">OK</button>
                        </div>
                    </div>
                </form>
            </div>
        <?php } else { ?>
            <div class="row">

                <div class="form-group col-lg-12">
                    <div class="col-lg-12">
                        <label>Bem Vindo</label>
                        <span class="text-center bg-info"><?= $_SESSION['player'] ?> </span>
                    </div>
                </div>
                <div class="form-group col-lg-12">
                    <div class="col-lg-12">
                        <a href="<?= $this->link('/cardgame/game'); ?>" class="form-control btn btn-primary">OK</a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>