<!DOCTYPE html>
<html>
    <header>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Demo - Projeto com Jaspion</title>
        <?= $this->css('bootstrap-theme.min') ?>"
        <?= $this->css('bootstrap.min') ?>
        <?= $this->css('padrao') ?>
        <?= $this->css('card') ?>
    </header>

    <body>

        <div>
            <div id="erro"></div>
            <div>
                <div class="panel panel-danger">
                    <div class="panel-heading "><span class="panel-title">Card Game</span></div>
                    <div class="panel-body" style="min-height: 500px;">
                        <div class='alerta'>
                            <?php echo $this->view->mensagem; ?>
                        </div>
                        <?php $this->content(); ?>
                    </div>
                </div>
            </div>

            <div class="modal fade modal_info">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header bg-success text-center" id="tipo_men">
                            <h3 class="modal-title text-center"><span id="titulo_men"> </span></h3>
                        </div>
                        <div class="modal-body">
                            <div id="informacao_men"></div>
                        </div>
                        <div class="modal-footer">
                            <div class="row">
                                <div class="col-lg-12 form-group">
                                    <div class="col-lg-12">
                                        <button class="btn btn-primary form-control" onclick="$('.modal_info').modal('hide');">OK</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?= $this->js('jquery-2.1.1.min') ?>
        <?= $this->js('bootstrap.min') ?>
        <?= $this->js('functions') ?>
        <?php $this->scripts(); ?>
    </body>
</html>